layout_spectrum: 0.7600251
typography_spectrum: 0.02168507
color:
  saturation: 0.1729002
  lightness: 0.4911019
  brandStrength: 0.4478589
  brandColors:
    - '#0D1518'
    - '#E8E1D7'
    - '#FFFFFF'
    - '#6E7777'
    - '#9AA39A'
  rhythmicContrast: 0.4191464
name: RIK ASSFALG MoM
